version: '3.3'

services:
  web:
    image: ghcr.io/pinbn/hosting-php:8.0
    restart: always
    deploy:
      labels:
        # Traefik 1:
        # - traefik.enable=true
        # - traefik.backend=testsite
        # - traefik.testsite.frontend.rule=Host:sitename.clientdomain.com
        # - traefik.port=80
        # Traefik 2:
        # - traefik.enable=true
        # - traefik.http.routers.testsite.rule=Host(`sitename.clientdomain.com`)
        # - traefik.http.routers.testsite.service=testsite
        # - traefik.http.services.testsite.loadbalancer.server.port=80
    networks:
      - traefik
    volumes:
      - /data/www/client/sitename/site:/var/www/html
      - /data/www/client/sitename/logs:/var/log/nginx
    environment:
      # This is default: - NGINX_USER=www-data

networks:
    traefik:
      external:
        name: traefik
        