version: '3.3'

services:
  web:
    image: ghcr.io/pinbn/hosting-images:php-8.1
    restart: always
    deploy:
      labels:
        # Traefik 1:
        # - traefik.enable=true
        # - traefik.backend=testsite
        # - traefik.testsite.frontend.rule=Host:sitename.clientdomain.com
        # - traefik.port=80
        # Traefik 2:
        # - traefik.enable=true
        # - traefik.http.routers.testsite.rule=Host(`sitename.clientdomain.com`)
        # - traefik.http.routers.testsite.service=testsite
        # - traefik.http.services.testsite.loadbalancer.server.port=80
    networks:
      - traefik
    volumes:
      - /data/www/client/sitename/site:/var/www/html
      - /data/www/client/sitename/logs:/var/log/nginx
    environment:
      # These are defaults and apply to all images:
      - NGINX_UID=33
      - NGINX_GID=33
      - upload_max_filesize=20M
      # These are defaults and only apply to php-* images (not plain):
      - php_max_execution_time=300
      - php_input_time=300
      - php_memory_limit=20M
      - php_timezone=America/Denver
      - php_allow_url_fopen=Off
      - php_smtp_server=localhost
      - php_smtp_port=25
      - php_smtp_log=/var/log/php.mail.log
      - php_session_handler=files
      - php_session_path=/tmp

networks:
    traefik:
      external:
        name: traefik
        