name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '20 8 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./php-5.6/Dockerfile
            image: ghcr.io/${{ github.repository }}:5.6
            tag: 5.6
          - dockerfile: ./php-5.6-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:5.6-wordpress
            tag: 5.6-wordpress
          - dockerfile: ./php-7.0/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.0
            tag: 7.0
          - dockerfile: ./php-7.0-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.0-wordpress
            tag: 7.0-wordpress
          - dockerfile: ./php-7.1/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.1
            tag: 7.1
          - dockerfile: ./php-7.1-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.1-wordpress
            tag: 7.1-wordpress
          - dockerfile: ./php-7.2/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.2
            tag: 7.2
          - dockerfile: ./php-7.2-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.2-wordpress
            tag: 7.2-wordpress
          - dockerfile: ./php-7.3/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.3
            tag: 7.3
          - dockerfile: ./php-7.3-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.3-wordpress
            tag: 7.3-wordpress
          - dockerfile: ./php-7.4/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.4
            tag: 7.4
          - dockerfile: ./php-7.4-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:7.4-wordpress
            tag: 7.4-wordpress
          - dockerfile: ./php-8.0/Dockerfile
            image: ghcr.io/${{ github.repository }}:8.0
            tag: 8.0
          - dockerfile: ./php-8.0-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:8.0-wordpress
            tag: 8.0-wordpress
          - dockerfile: ./php-8.1/Dockerfile
            image: ghcr.io/${{ github.repository }}:8.1
            tag: 8.1
          - dockerfile: ./php-8.1-wordpress/Dockerfile
            image: ghcr.io/${{ github.repository }}:8.1-wordpress
            tag: 8.1-wordpress
          - dockerfile: ./plain/Dockerfile
            image: ghcr.io/${{ github.repository }}:plain
            tag: plain
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

# Not used at this time
#      # Install the cosign tool except on PR
#      # https://github.com/sigstore/cosign-installer
#      - name: Install cosign
#        if: github.event_name != 'pull_request'
#        uses: sigstore/cosign-installer@d6a3abf1bdea83574e28d40543793018b6035605
#        with:
#          cosign-release: 'v1.7.1'

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ matrix.image }}
          #labels: ${{ steps.meta.outputs.labels }}

# Not used at this time
#      # Sign the resulting Docker image digest except on PRs.
#      # This will only write to the public Rekor transparency log when the Docker
#      # repository is public to avoid leaking data.  If you would like to publish
#      # transparency data even for private images, pass --force to cosign below.
#      # https://github.com/sigstore/cosign
#      - name: Sign the published Docker image
#        if: ${{ github.event_name != 'pull_request' }}
#        env:
#          COSIGN_EXPERIMENTAL: "true"
#        # This step uses the identity token to provision an ephemeral certificate
#        # against the sigstore community Fulcio instance.
#        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
